version: "3"

services:
  api:
    container_name: prod_api
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    container_name: prod_db_postgres
    image: postgres
    env_file:
      - ./.env
    volumes:
      - postgres-db-prod:/var/lib/postgresql/data

volumes:
  postgres-db-prod:
