"""add phone number

Revision ID: 4092454ba0ea
Revises: dbf0a363b0ef
Create Date: 2022-01-22 20:28:38.024535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4092454ba0ea'
down_revision = 'dbf0a363b0ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
